#!/usr/bin/env bash
set -ex

# make sure pkg source files are up to date with repo
cd /opt/MUSO_bld/pkg
cp -fpru MUSO/Builds/containers/packaging/dpkg/debian/. debian/
cp -fpu MUSO/Builds/containers/shared/MUSO.service debian/
cp -fpu MUSO/Builds/containers/shared/update_sources.sh .
source update_sources.sh

# Build the dpkg

#dpkg uses - as separator, so we need to change our -bN versions to tilde
MUSO_DPKG_VERSION=$(echo "${MUSO_VERSION}" | sed 's!-!~!g')
# TODO - decide how to handle the trailing/release
# version here (hardcoded to 1). Does it ever need to change?
MUSO_DPKG_FULL_VERSION="${MUSO_DPKG_VERSION}-1"

cd /opt/MUSO_bld/pkg/MUSO
if [[ -n $(git status --porcelain) ]]; then
    git status
    error "Unstaged changes in this repo - please commit first"
fi
git archive --format tar.gz --prefix MUSO-${MUSO_DPKG_VERSION}/ -o ../MUSO-${MUSO_DPKG_VERSION}.tar.gz HEAD
cd ..
# dpkg debmake would normally create this link, but we do it manually
ln -s ./MUSO-${MUSO_DPKG_VERSION}.tar.gz MUSO_${MUSO_DPKG_VERSION}.orig.tar.gz
tar xvf MUSO-${MUSO_DPKG_VERSION}.tar.gz
cd MUSO-${MUSO_DPKG_VERSION}
cp -pr ../debian .

# dpkg requires a changelog. We don't currently maintain
# a useable one, so let's just fake it with our current version
# TODO : not sure if the "unstable" will need to change for
# release packages (?)
NOWSTR=$(TZ=UTC date -R)
cat << CHANGELOG > ./debian/changelog
MUSO (${MUSO_DPKG_FULL_VERSION}) unstable; urgency=low

  * see RELEASENOTES

 -- MUSO Labs Inc. <support@MUSO.com>  ${NOWSTR}
CHANGELOG

# PATH must be preserved for our more modern cmake in /opt/local
# TODO : consider allowing lintian to run in future ?
export DH_BUILD_DDEBS=1
export CC=gcc-8
export CXX=g++-8
debuild --no-lintian --preserve-envvar PATH --preserve-env -us -uc
rc=$?; if [[ $rc != 0 ]]; then
    error "error building dpkg"
fi
cd ..
ls -latr

# copy artifacts
cp MUSO-dev_${MUSO_DPKG_FULL_VERSION}_amd64.deb ${PKG_OUTDIR}
cp MUSO_${MUSO_DPKG_FULL_VERSION}_amd64.deb ${PKG_OUTDIR}
cp MUSO_${MUSO_DPKG_FULL_VERSION}.dsc ${PKG_OUTDIR}
# dbgsym suffix is ddeb under newer debuild, but just deb under earlier
cp MUSO-dbgsym_${MUSO_DPKG_FULL_VERSION}_amd64.* ${PKG_OUTDIR}
cp MUSO_${MUSO_DPKG_FULL_VERSION}_amd64.changes ${PKG_OUTDIR}
cp MUSO_${MUSO_DPKG_FULL_VERSION}_amd64.build ${PKG_OUTDIR}
cp MUSO_${MUSO_DPKG_VERSION}.orig.tar.gz ${PKG_OUTDIR}
cp MUSO_${MUSO_DPKG_FULL_VERSION}.debian.tar.xz ${PKG_OUTDIR}
# buildinfo is only generated by later version of debuild
if [ -e MUSO_${MUSO_DPKG_FULL_VERSION}_amd64.buildinfo ] ; then
    cp MUSO_${MUSO_DPKG_FULL_VERSION}_amd64.buildinfo ${PKG_OUTDIR}
fi

cat MUSO_${MUSO_DPKG_FULL_VERSION}_amd64.changes
# extract the text in the .changes file that appears between
#    Checksums-Sha256:  ...
# and
#    Files: ...
awk '/Checksums-Sha256:/{hit=1;next}/Files:/{hit=0}hit' \
    MUSO_${MUSO_DPKG_VERSION}-1_amd64.changes | \
        sed -E 's!^[[:space:]]+!!' > shasums
DEB_SHA256=$(cat shasums | \
    grep "MUSO_${MUSO_DPKG_VERSION}-1_amd64.deb" | cut -d " " -f 1)
DBG_SHA256=$(cat shasums | \
    grep "MUSO-dbgsym_${MUSO_DPKG_VERSION}-1_amd64.*" | cut -d " " -f 1)
DEV_SHA256=$(cat shasums | \
    grep "MUSO-dev_${MUSO_DPKG_VERSION}-1_amd64.deb" | cut -d " " -f 1)
SRC_SHA256=$(cat shasums | \
    grep "MUSO_${MUSO_DPKG_VERSION}.orig.tar.gz" | cut -d " " -f 1)
echo "deb_sha256=${DEB_SHA256}" >> ${PKG_OUTDIR}/build_vars
echo "dbg_sha256=${DBG_SHA256}" >> ${PKG_OUTDIR}/build_vars
echo "dev_sha256=${DEV_SHA256}" >> ${PKG_OUTDIR}/build_vars
echo "src_sha256=${SRC_SHA256}" >> ${PKG_OUTDIR}/build_vars
echo "MUSO_version=${MUSO_VERSION}" >> ${PKG_OUTDIR}/build_vars
echo "dpkg_version=${MUSO_DPKG_VERSION}" >> ${PKG_OUTDIR}/build_vars
echo "dpkg_full_version=${MUSO_DPKG_FULL_VERSION}" >> ${PKG_OUTDIR}/build_vars

